### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by ghost** [mkschleg/auto-soft-wrap#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.4
**Thrown From**: [auto-soft-wrap](https://github.com/mkschleg/auto-soft-wrap) package, v0.2.3
### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of undefined

```
At /Users/angelaji/.atom/packages/auto-soft-wrap/lib/auto-soft-wrap.coffee:28

TypeError: Cannot read property 'substr' of undefined
    at didChangeActiveItemInPane (/Users/angelaji/.atom/packages/auto-soft-wrap/lib/auto-soft-wrap.coffee:28:21)
    at Function.module.exports.Emitter.simpleDispatch (/Users/angelaji/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/angelaji/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/angelaji/Downloads/Atom.app/Contents/Resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/Users/angelaji/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/angelaji/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Users/angelaji/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:282:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/Users/angelaji/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:414:19)
    at Pane.module.exports.Pane.activatePreviousItem (/Users/angelaji/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:379:21)
    at Pane.module.exports.Pane.removeItem (/Users/angelaji/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:564:16)
    at Pane.module.exports.Pane.destroyItem (/Users/angelaji/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:637:16)
    at atom-tabs.TabBarView.onClick (/Users/angelaji/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:688:17)
```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
auto-soft-wrap, v0.2.3
color-picker, v2.1.1
emmet, v2.4.3
file-icons, v1.7.12

# Dev
No dev packages
```

**Comment by leroycep** [comment]
I am having this problem too. I think it happens when you switch to a file that is not saved.

**Comment by mkschleg** [comment]
OK! Should be a simple fix. I'll look into it by the end of the weekend! Break just started so haven't wanted to work on things for the past few days.

**Comment by mkschleg** [comment]
Thanks @Geemili for the fix. Should be up and ready to use.
