### ISSUE TITLE
Uncaught TypeError: item.setSoftWrapped is not a function

### ISSUE THREAD

**Issue by dshafik** [mkschleg/auto-soft-wrap#3]
[Enter steps to reproduce below:]
1. Close document
2. Close markdown preview
3. Alert pops up

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [auto-soft-wrap](https://github.com/mkschleg/auto-soft-wrap) package, v0.3.0
### Stack Trace

Uncaught TypeError: item.setSoftWrapped is not a function

```
At /Users/dshafik/.atom/packages/auto-soft-wrap/lib/auto-soft-wrap.coffee:32

TypeError: item.setSoftWrapped is not a function
    at didChangeActiveItemInPane (/Users/dshafik/.atom/packages/auto-soft-wrap/lib/auto-soft-wrap.coffee:32:12)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:282:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:414:19)
    at Pane.module.exports.Pane.activateNextItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:369:21)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:562:16)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:637:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/markdown-preview/lib/markdown-preview-view.js:103:106
    at MarkdownPreviewView.module.exports.MarkdownPreviewView.resolveEditor (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/markdown-preview/lib/markdown-preview-view.js:108:16)
    at MarkdownPreviewView.module.exports.MarkdownPreviewView.attached (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/markdown-preview/lib/markdown-preview-view.js:44:21)
    at space-pen-div.View.element.attached (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:164:63)
    at space-pen-div.CustomElementPrototype.attachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:51:55)
    at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:138:24)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:282:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:414:19)
    at Pane.module.exports.Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:379:21)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:564:16)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:637:16)
    at atom-tabs.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:688:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "highlight-line",
      "markdown-document",
      "linter-markdown"
    ],
    "themes": [
      "one-light-ui",
      "monokai-light"
    ]
  },
  "auto-soft-wrap": {
    "softWrapFileTypes": [
      ".tex",
      ".txt",
      ".asciidoc",
      ".md"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
asciidoc-assistant, v0.2.1
asciidoc-image-helper, v1.0.0
asciidoc-preview, v2.5.2
auto-soft-wrap, v0.3.0
autoclose-html, v0.23.0
autocomplete-asciidoc, v0.1.1
color-picker, v2.2.2
double-tag, v0.2.0
file-icons, v1.7.17
highlight-selected, v0.11.2
language-asciidoc, v1.5.1
linter, v1.11.14
linter-write-good, v0.6.1
markdown-scroll-sync, v2.1.2
markdown-writer, v2.4.0
monokai-light, v0.3.7
open-recent, v5.0.0
pigments, v0.31.1

# Dev
No dev packages
```

**Comment by mkschleg** [comment]
Does it only happen with Markdown preview? I'm not able to replicate the error.

**Comment by mkschleg** [comment]
Should have been fixed. Re-open if it is not.
